### ISSUE TITLE
Allocating mem for salesman_trip

### ISSUE THREAD

**Issue by Stevo15025** [Stevo15025/tsp_gpu#2]
@PB12203006 
Should the size of the salesman's trip (for device memory at least) be equal to `N * t_num`?

As the code currently reads `salesman_route` is currently of size `N`, the number of cities. And we want each thread to return it's proposal route. So should the `salesman_route_g` be equal to `N * t_num`?

So we'll have an initial route `salesman_route`, then the device routes `salesman_route_g` that is `salesman_route` repeated `t_num` times for each thread. We'll do the kernel and then check for an acceptance. If we see an acceptance, we'll copy the winning trip from `salesman_route_g` into `salesman_route` and repeat until `T` drops to below 1.

**Comment by PB12203006** [comment]
I had an intuitive analysis. Although this method could avoid conflict on accessing the global memory at the beginning, after each iteration, we have to copy the accepted route to the other routes, this additional step may also cause the accessing conflict. So it's not perfect, either.
But I think it's worth trying because this is only one intuitive analysis, not quantitative. I like one saying of communist party, practice is the sole criterion for testing truth.

**Comment by PB12203006** [comment]
Oh I made a mistake, only exchanging the accepted city-swap is enough, yes, it looks like a better idea!

**Comment by Stevo15025** [comment]
@PB12203006 I took a swing at this, but I think my version of cuda is not installed correctly. Can you pull this and try it on your computer?

Oh also I have `printf("Current Temperature is: %.6f:", T);` in the while loop so it's going to look like the matrix in your terminal fyi

**Comment by Stevo15025** [comment]
Resolved in commit  e42be48
