### ISSUE TITLE
Wrong output

### ISSUE THREAD

**Issue by PB12203006** [Stevo15025/tsp_gpu#5]
The y coordinate of locations recorded in the output, mona_lisa_best_trip.csv is obviously wrong.

1.  location 99999 has a negative y
2.  The range of y is different from the input data

**Comment by PB12203006** [comment]
I've tested the read function, it's wrong. Its out put y=i+1.

**Comment by PB12203006** [comment]
Why not try mine simple read function, I'm convinced it is correct!

**Comment by Stevo15025** [comment]
Reaing in `ch130.tsp` and printing it with

```
    for (i = 0; i < N; i++)
      printf("Location x: %0.6f, location y: %0.6f \n", location[i].x, location[i].y);
```
gives 
```
found section contaning the node coordinates
Location x: 0.590925, location y: 161.780930 
Location x: 397.644653, location y: 262.816528 
Location x: 503.874176, location y: 172.874115 
Location x: 444.047943, location y: 384.649170 
...
Location x: 566.564575, location y: 199.955154 
Location x: 196.684921, location y: 221.820923 
Location x: 384.927032, location y: 87.463020 
Location x: 178.110779, location y: 104.690582 
Location x: 403.287445, location y: 205.897171 
```

Where the original output is

```
NODE_COORD_SECTION
1 334.5909245845 161.7809319139
2 397.6446634067 262.8165330708
3 503.8741827107 172.8741151168
4 444.0479403502 384.6491809647
...
126 566.5645610042 199.9551615873
127 196.6849168280 221.8209157619
128 384.9270448985 87.4630166986
129 178.1107815614 104.6905805938
130 403.2874386776 205.8971749407
```

So the current method is missing 334 at the beginning, which I'll fix right now. The false output in the csv must be due to incorrectly outputting the csv.

We are currently doing 
```{C}
    FILE *best_trip;
    const char *filename="mona_lisa_best_trip.csv";
    best_trip = fopen(filename,"w+");
    fprintf(best_trip, "location, coordinate_x, coordinate_y \n");
    for (i = 0; i < N + 1; i++){
        fprintf(best_trip, "%d, %.6f, %.6f \n",
                salesman_route[i],
                location[salesman_route[i]].x,
                location[salesman_route[i]].y);
    }
    fclose(best_trip);
```

It may just be that we need to put ` %0.6f, %0.6f` instead of ` %.6f, %.6f`.

I'll do this right now. While your read in is correct I think we should keep the meta information such as the number of observations. Also, keep in mind that our current kernel only works for euclidian 2d distances. We may want to write other kernels in the future that read in `EDGE_WEIGHT_TYPE:` and use a kernel with a different loss function, for example euclidian 3d distances. Did yours read in the meta information?

**Comment by Stevo15025** [comment]
Fixed in  774515e

**Comment by PB12203006** [comment]
I'm a little confused but discussing face to face is better. Now I'm focusing on coding the "inserting" method. It's complicated, hope I could achieve before meeting.

**Comment by Stevo15025** [comment]
@PB12203006 I may be 5 minutes late to the meeting.

**Comment by PB12203006** [comment]
No problem, I'm in the nwc library now, contact me when you arrive.
